### PR TITLE
Added multi-input support to moviepy backend.

### PR DESCRIPTION
**Pull request by Sv3n**
Still has a bug where the sound plays OVER the spacer banner, causing the question to run out of sound right before the end of the question. Also seems to repeat 1 second of audio at the very end of a clip.

### CODE REVIEW

**Comment by CNugteren** [comment]
Isn't the issue that the `add_spacer` is only called in the video stream and thus the audio stream doesn't get an empty X seconds added? This seems also an issue with the FFMPEG back-end, but it hasn't shown yet because it doesn't support the spacers (yet).

**Comment by Sv3n** [comment]
I didn't implement `add_silence` yet. Doing that now, I expect it solves the issue.

**Comment by Sv3n** [comment]
The small audio glitches between video's are still there, I suspect they might be caused by some rounding errors here and there when concatenating clips and overlaying audio. I can experiment a bit to see if it can be solved, but the main purpose of this PR is implemented, so I think it can be merged.

**Comment by CNugteren** [comment]
Agree, everything looks good. Go ahead!

**Pull request merged**
